version: '3.8'

services:
 app:
  image: pritamgangarde/dockermysqldemo:0.0.1
  ports: 
  - 9192:9192
  
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/daksh?serverTimezone=UTC&useSSL=false&autoReconnect=true
   SPRING_DATASOURCE_USERNAME: admin
   SPRING_DATASOURCE_PASSWORD: root@123
   
  depends_on:
  - db
  

 db:
  image: mysql:8.0.27
  environment:
   DATABASE_HOST: docker_mysql
   DATABASE_PORT: 3306
   MYSQL_ROOT_PASSWORD: root@123
   MYSQL_DATABASE: daksh
   MYSQL_USER: admin
   MYSQL_PASSWORD: root@123